# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aux_Lohmann_conv <- function(tmpm) {
    .Call(`_VIC5_aux_Lohmann_conv`, tmpm)
}

vic_run_cell <- function(vic_options, forcing, soil_par, snowband, veg_par, lake_par, forcing_veg, veglib, output_info) {
    .Call(`_VIC5_vic_run_cell`, vic_options, forcing, soil_par, snowband, veg_par, lake_par, forcing_veg, veglib, output_info)
}

vic_run_cells_all <- function(vic_options, forcing_3d, soil_par_mat, veg_par_list, forcing_veg, snowband, lake_par, veglib, output_info, ncores = 2L) {
    .Call(`_VIC5_vic_run_cells_all`, vic_options, forcing_3d, soil_par_mat, veg_par_list, forcing_veg, snowband, lake_par, veglib, output_info, ncores)
}

#' Display version of VIC model and this package.
#'
#'
#' @export
vic_version <- function() {
    invisible(.Call(`_VIC5_vic_version`))
}

